<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260922060913 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE avis (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, note INT NOT NULL, commentaire TEXT DEFAULT NULL, rendez_vous_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8F91ABF091EF7EAA ON avis (rendez_vous_id)');
        $this->addSql('CREATE TABLE creneau (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, heure VARCHAR(50) NOT NULL, disponible BOOLEAN NOT NULL, service_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F9668B5FED5CA9E6 ON creneau (service_id)');
        $this->addSql('CREATE TABLE demande (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, text_demande TEXT NOT NULL, status VARCHAR(50) NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, confiance DOUBLE PRECISION DEFAULT NULL, utilisateur_id INT NOT NULL, service_recommande_id INT DEFAULT NULL, service_final_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2694D7A5FB88E14F ON demande (utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_2694D7A55CFFB16F ON demande (service_recommande_id)');
        $this->addSql('CREATE INDEX IDX_2694D7A5EAA24010 ON demande (service_final_id)');
        $this->addSql('CREATE TABLE document_requis (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(50) NOT NULL, obligatoire BOOLEAN NOT NULL, remarque TEXT DEFAULT NULL, procedure_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E412D9181624BCD2 ON document_requis (procedure_id)');
        $this->addSql('CREATE TABLE etape_procedure (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ordre INT NOT NULL, descripton TEXT NOT NULL, procedure_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B12F09F01624BCD2 ON etape_procedure (procedure_id)');
        $this->addSql('CREATE TABLE historique_statut (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, statut VARCHAR(50) NOT NULL, date_changement TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, demande_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2C2650E380E95E18 ON historique_statut (demande_id)');
        $this->addSql('CREATE TABLE journal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(50) NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, adresse_ip VARCHAR(50) NOT NULL, utilisateur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C1A7E74DFB88E14F ON journal (utilisateur_id)');
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, canal VARCHAR(50) NOT NULL, message TEXT NOT NULL, statut VARCHAR(50) NOT NULL, date_envoi TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, utilisateur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF5476CAFB88E14F ON notification (utilisateur_id)');
        $this->addSql('CREATE TABLE procedure (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(50) NOT NULL, description TEXT DEFAULT NULL, delai_estime INT DEFAULT NULL, frais VARCHAR(50) DEFAULT NULL, version VARCHAR(50) DEFAULT NULL, service_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9C3CBC1FED5CA9E6 ON procedure (service_id)');
        $this->addSql('CREATE TABLE rendez_vous (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, statut VARCHAR(50) NOT NULL, demande_id INT NOT NULL, creaneau_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_65E8AA0A80E95E18 ON rendez_vous (demande_id)');
        $this->addSql('CREATE INDEX IDX_65E8AA0AB8BBCB9E ON rendez_vous (creaneau_id)');
        $this->addSql('CREATE TABLE role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE service (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(50) NOT NULL, mission VARCHAR(50) DEFAULT NULL, categorie VARCHAR(50) DEFAULT NULL, adresse VARCHAR(50) DEFAULT NULL, horaires VARCHAR(50) DEFAULT NULL, contact VARCHAR(50) DEFAULT NULL, actif BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE utilisateur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(50) NOT NULL, prenom VARCHAR(50) NOT NULL, email VARCHAR(50) NOT NULL, password VARCHAR(50) NOT NULL, role_id INT NOT NULL, service_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1D1C63B3D60322AC ON utilisateur (role_id)');
        $this->addSql('CREATE INDEX IDX_1D1C63B3ED5CA9E6 ON utilisateur (service_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE avis ADD CONSTRAINT FK_8F91ABF091EF7EAA FOREIGN KEY (rendez_vous_id) REFERENCES rendez_vous (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE creneau ADD CONSTRAINT FK_F9668B5FED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE demande ADD CONSTRAINT FK_2694D7A5FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE demande ADD CONSTRAINT FK_2694D7A55CFFB16F FOREIGN KEY (service_recommande_id) REFERENCES service (id)');
        $this->addSql('ALTER TABLE demande ADD CONSTRAINT FK_2694D7A5EAA24010 FOREIGN KEY (service_final_id) REFERENCES service (id)');
        $this->addSql('ALTER TABLE document_requis ADD CONSTRAINT FK_E412D9181624BCD2 FOREIGN KEY (procedure_id) REFERENCES procedure (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE etape_procedure ADD CONSTRAINT FK_B12F09F01624BCD2 FOREIGN KEY (procedure_id) REFERENCES procedure (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE historique_statut ADD CONSTRAINT FK_2C2650E380E95E18 FOREIGN KEY (demande_id) REFERENCES demande (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE journal ADD CONSTRAINT FK_C1A7E74DFB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAFB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE procedure ADD CONSTRAINT FK_9C3CBC1FED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rendez_vous ADD CONSTRAINT FK_65E8AA0A80E95E18 FOREIGN KEY (demande_id) REFERENCES demande (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rendez_vous ADD CONSTRAINT FK_65E8AA0AB8BBCB9E FOREIGN KEY (creaneau_id) REFERENCES creneau (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE utilisateur ADD CONSTRAINT FK_1D1C63B3D60322AC FOREIGN KEY (role_id) REFERENCES role (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE utilisateur ADD CONSTRAINT FK_1D1C63B3ED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE avis DROP CONSTRAINT FK_8F91ABF091EF7EAA');
        $this->addSql('ALTER TABLE creneau DROP CONSTRAINT FK_F9668B5FED5CA9E6');
        $this->addSql('ALTER TABLE demande DROP CONSTRAINT FK_2694D7A5FB88E14F');
        $this->addSql('ALTER TABLE demande DROP CONSTRAINT FK_2694D7A55CFFB16F');
        $this->addSql('ALTER TABLE demande DROP CONSTRAINT FK_2694D7A5EAA24010');
        $this->addSql('ALTER TABLE document_requis DROP CONSTRAINT FK_E412D9181624BCD2');
        $this->addSql('ALTER TABLE etape_procedure DROP CONSTRAINT FK_B12F09F01624BCD2');
        $this->addSql('ALTER TABLE historique_statut DROP CONSTRAINT FK_2C2650E380E95E18');
        $this->addSql('ALTER TABLE journal DROP CONSTRAINT FK_C1A7E74DFB88E14F');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAFB88E14F');
        $this->addSql('ALTER TABLE procedure DROP CONSTRAINT FK_9C3CBC1FED5CA9E6');
        $this->addSql('ALTER TABLE rendez_vous DROP CONSTRAINT FK_65E8AA0A80E95E18');
        $this->addSql('ALTER TABLE rendez_vous DROP CONSTRAINT FK_65E8AA0AB8BBCB9E');
        $this->addSql('ALTER TABLE utilisateur DROP CONSTRAINT FK_1D1C63B3D60322AC');
        $this->addSql('ALTER TABLE utilisateur DROP CONSTRAINT FK_1D1C63B3ED5CA9E6');
        $this->addSql('DROP TABLE avis');
        $this->addSql('DROP TABLE creneau');
        $this->addSql('DROP TABLE demande');
        $this->addSql('DROP TABLE document_requis');
        $this->addSql('DROP TABLE etape_procedure');
        $this->addSql('DROP TABLE historique_statut');
        $this->addSql('DROP TABLE journal');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE procedure');
        $this->addSql('DROP TABLE rendez_vous');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE service');
        $this->addSql('DROP TABLE utilisateur');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
